"use client";
import { useEffect,useState } from "react";
import { ArrowLeft, Check, ChevronRight, ClipboardList, Download, FileText, Home, Plus, Search, Settings, Trash2, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { NativeSelect,NativeSelectOption } from "@/components/ui/native-select";
import DocEditor,{Field} from "@/components/doc-editor";
import PrintSheet from "@/components/print-sheet";
import { Business,Client,Doc,Photo,blankBusiness,blankClient,blankDoc,provinces,cash,today,totals,readBusiness,readClient,readDoc,mutate,item } from "@/lib/model";
type View="home"|"estimates"|"invoices"|"clients"|"settings"|"client"|"document";
function Status({value}:{value:string}){return <span className={"status status-"+value}>{value}</span>}
function Empty({title,detail,action}:{title:string;detail:string;action?:React.ReactNode}){return <div className="empty"><div className="empty-icon"><ClipboardList size={25}/></div><h3>{title}</h3><p>{detail}</p>{action}</div>}
export default function HomePage(){
 const [view,setView]=useState<View>("home"),[clients,setClients]=useState<Client[]>([]),[documents,setDocuments]=useState<Doc[]>([]),[photos,setPhotos]=useState<Photo[]>([]);
 const [business,setBusiness]=useState<Business>(blankBusiness),[client,setClient]=useState<Client|null>(null),[doc,setDoc]=useState<Doc|null>(null),[printDoc,setPrintDoc]=useState<Doc|null>(null);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[search,setSearch]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function refresh(){const response=await fetch("/api/data",{cache:"no-store"});const data=await response.json() as {error?:string;clients?:Record<string,unknown>[];documents?:Record<string,unknown>[];photos?:Record<string,unknown>[];settings:Record<string,unknown>|null};if(!response.ok)throw new Error(data.error||"Could not load data.");setClients((data.clients||[]).map(readClient));setDocuments((data.documents||[]).map(readDoc));setPhotos((data.photos||[]).map((p:Record<string,unknown>)=>({id:String(p.id),documentId:String(p.document_id),filename:String(p.filename)})));setBusiness(readBusiness(data.settings))}
 useEffect(()=>{refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{
   type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:()=>{view:string}};
   const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
   if(!context?.registerTool)return;
   const lifecycle=new AbortController();
   for(const [name,title,target] of [["open_estimates","Open estimates","estimates"],["open_clients","Open clients","clients"]] as const){
     void Promise.resolve(context.registerTool({name,title,description:"Open the "+target+" list in Grand Terra Estimates.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>{setView(target);return{view:target}}},{signal:lifecycle.signal})).catch(console.error);
   }
   return()=>lifecycle.abort();
 },[]);
 function flash(s:string){setNotice(s);setTimeout(()=>setNotice(""),3500)}
 function go(v:View){setView(v);setSearch("");setError("");window.scrollTo({top:0,behavior:"smooth"})}
 function editClient(c?:Client){setClient(c?{...c}:blankClient());go("client")}
 function editDoc(d?:Doc,kind:"estimate"|"invoice"="estimate"){setDoc(d?{...d,items:d.items.map(i=>({...i}))}:blankDoc(kind,business));go("document")}
 async function saveClient(){if(!client?.name.trim()){setError("Enter a client name.");return}setSaving(true);setError("");try{await mutate("saveClient",client,client.id);await refresh();flash("Client saved");go("clients")}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function saveDoc(){if(!doc?.clientId){setError("Select a saved client.");return}const selected=clients.find(c=>c.id===doc.clientId);if(!selected){setError("Select a saved client.");return}setSaving(true);setError("");try{const value={...doc,clientSnapshot:selected};const result=await mutate("saveDocument",value,doc.id);setDoc({...value,id:String(result.id||"")});await refresh();flash("Document saved")}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function saveBusiness(){setSaving(true);setError("");try{await mutate("saveSettings",business);flash("Business details saved")}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function removeClient(){if(!client||!confirm("Delete this client? Saved documents keep a copy of the client details."))return;try{await mutate("deleteClient",{},client.id);await refresh();go("clients");flash("Client deleted")}catch(e){setError((e as Error).message)}}
 async function removeDoc(){if(!doc||!confirm("Permanently delete this document and its photos?"))return;try{await mutate("deleteDocument",{},doc.id);await refresh();go(doc.kind==="invoice"?"invoices":"estimates");flash("Document deleted")}catch(e){setError((e as Error).message)}}
 async function upload(file?:File){if(!file||!doc?.id)return;setSaving(true);setError("");try{const form=new FormData();form.append("documentId",doc.id);form.append("file",file);const response=await fetch("/api/photos",{method:"POST",body:form});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"Upload failed");await refresh();flash("Photo added")}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function deletePhoto(p:Photo){if(!confirm("Delete this photo?"))return;try{const response=await fetch("/api/photos?id="+encodeURIComponent(p.id),{method:"DELETE"});if(!response.ok)throw new Error("Could not delete photo.");await refresh();flash("Photo deleted")}catch(e){setError((e as Error).message)}}
 function duplicate(kind?: "estimate"|"invoice"){if(!doc)return;const k=kind||doc.kind;setDoc({...doc,id:"",kind:k,number:(k==="invoice"?"INV":"EST")+"-"+new Date().getFullYear()+"-"+String(Date.now()).slice(-5),status:"draft",issueDate:today(),dueDate:"",depositCents:0,items:doc.items.map(i=>({...i,id:crypto.randomUUID()}))});window.scrollTo({top:0,behavior:"smooth"})}
 function print(d:Doc){setPrintDoc(d);setTimeout(()=>window.print(),250)}
 function backup(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),clients,documents,business},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="grand-terra-backup-"+today()+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 const kind=view==="invoices"?"invoice":"estimate";
 const filteredDocs=documents.filter(d=>d.kind===kind&&(d.number+" "+d.title+" "+(clients.find(c=>c.id===d.clientId)?.name||d.clientSnapshot.name||"")).toLowerCase().includes(search.toLowerCase()));
 const filteredClients=clients.filter(c=>(c.name+" "+c.company+" "+c.email+" "+c.phone).toLowerCase().includes(search.toLowerCase()));
 const outstanding=documents.filter(d=>d.kind==="invoice"&&d.status!=="paid").reduce((s,d)=>s+totals(d).balance,0);
 const pipeline=documents.filter(d=>d.kind==="estimate"&&["draft","sent"].includes(d.status)).reduce((s,d)=>s+totals(d).total,0);
 const nav=([["home",Home,"Overview"],["estimates",ClipboardList,"Estimates"],["invoices",FileText,"Invoices"],["clients",Users,"Clients"],["settings",Settings,"Settings"]] as const);
 return <><div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">GT</div><div><strong>GRAND TERRA</strong><span>ESTIMATES</span></div></div><nav aria-label="Main navigation">{nav.map(([v,Icon,label])=><button key={v} className={"nav-item "+(view===v?"active":"")} onClick={()=>go(v)}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="sidebar-foot"><span className="online-dot"/> Private workspace<br/><small>Grand Terra · Canada</small></div></aside>
 <main className="main"><header className="topbar"><div className="mobile-brand"><div className="brand-mark">GT</div><strong>GRAND TERRA</strong></div><div className="topbar-title">{view==="document"?(doc?.kind==="invoice"?"Invoice editor":"Estimate editor"):view==="client"?"Client details":view==="home"?"Overview":view[0].toUpperCase()+view.slice(1)}</div><div className="topbar-actions"><span>Contractor workspace</span><div className="avatar">GT</div></div></header><div className="content">
 {error&&<div role="alert" className="banner error"><span>{error}</span><button aria-label="Dismiss" onClick={()=>setError("")}><X size={17}/></button></div>}{notice&&<div role="status" className="banner success"><Check size={17}/>{notice}</div>}
 {loading?<div className="loading">Loading your workspace…</div>:view==="home"?<>
 <div className="page-heading"><div><div className="eyebrow">YOUR WORKSPACE</div><h1>Good to have you here.</h1><p>Quotes, invoices, and client details in one place.</p></div><Button className="primary-button" onClick={()=>editDoc()}><Plus size={18}/> New estimate</Button></div>
 <div className="quick-actions"><button onClick={()=>editDoc()}><span className="quick-icon blue"><ClipboardList size={21}/></span><span><strong>Create estimate</strong><small>Build a quote in minutes</small></span><ChevronRight size={18}/></button><button onClick={()=>editDoc(undefined,"invoice")}><span className="quick-icon green"><FileText size={21}/></span><span><strong>Create invoice</strong><small>Bill a client or job</small></span><ChevronRight size={18}/></button><button onClick={()=>editClient()}><span className="quick-icon gold"><Users size={21}/></span><span><strong>Add client</strong><small>Save contact details</small></span><ChevronRight size={18}/></button></div>
 <div className="stats"><div className="stat"><span>Active estimates</span><strong>{documents.filter(d=>d.kind==="estimate"&&["draft","sent"].includes(d.status)).length}</strong><small>{cash(pipeline)} in pipeline</small></div><div className="stat"><span>Outstanding invoices</span><strong>{documents.filter(d=>d.kind==="invoice"&&d.status!=="paid").length}</strong><small>{cash(outstanding)} to collect</small></div><div className="stat"><span>Saved clients</span><strong>{clients.length}</strong><small>Ready for your next job</small></div></div>
 <section className="section"><div className="section-head"><div><h2>Recent documents</h2><p>Pick up where you left off.</p></div><button className="text-action" onClick={()=>go("estimates")}>View estimates <ChevronRight size={16}/></button></div>{documents.length?<div className="record-list">{documents.slice(0,5).map(d=><button className="record" key={d.id} onClick={()=>editDoc(d)}><span className={"record-icon "+d.kind}><FileText size={21}/></span><span className="record-main"><strong>{d.title||d.number}</strong><small>{d.number} · {clients.find(c=>c.id===d.clientId)?.name||d.clientSnapshot.name||"No client"}</small></span><span className="record-side"><strong>{cash(totals(d).total)}</strong><Status value={d.status}/></span><ChevronRight size={17}/></button>)}</div>:<Empty title="No documents yet" detail="Create an estimate to start your project history." action={<Button onClick={()=>editDoc()}><Plus size={17}/> New estimate</Button>}/>}</section>
 </>:view==="estimates"||view==="invoices"?<>
 <div className="page-heading"><div><div className="eyebrow">DOCUMENTS</div><h1>{view==="invoices"?"Invoices":"Estimates"}</h1><p>{view==="invoices"?"Track billing and payments.":"Create, revise, and track client quotes."}</p></div><Button className="primary-button" onClick={()=>editDoc(undefined,kind)}><Plus size={18}/> New {kind}</Button></div>
 <div className="toolbar"><div className="search"><Search size={18}/><Input aria-label={"Search "+view} placeholder="Search client, title, or number" value={search} onChange={e=>setSearch(e.target.value)}/></div><span>{filteredDocs.length} {kind}{filteredDocs.length===1?"":"s"}</span></div>
 {filteredDocs.length?<div className="record-list">{filteredDocs.map(d=><button className="record" key={d.id} onClick={()=>editDoc(d)}><span className={"record-icon "+d.kind}><FileText size={21}/></span><span className="record-main"><strong>{d.title||d.number}</strong><small>{d.number} · {clients.find(c=>c.id===d.clientId)?.name||d.clientSnapshot.name||"No client"} · {d.issueDate}</small></span><span className="record-side"><strong>{cash(totals(d).total)}</strong><Status value={d.status}/></span><ChevronRight size={17}/></button>)}</div>:<Empty title={search?"No matching documents":"No "+view+" yet"} detail={search?"Try a different search.":"Create your first "+kind+" to get started."} action={!search?<Button onClick={()=>editDoc(undefined,kind)}><Plus size={17}/> New {kind}</Button>:undefined}/>}
 </>:view==="clients"?<>
 <div className="page-heading"><div><div className="eyebrow">CONTACTS</div><h1>Clients</h1><p>Keep contact and job addresses ready for every quote.</p></div><Button className="primary-button" onClick={()=>editClient()}><Plus size={18}/> Add client</Button></div>
 <div className="toolbar"><div className="search"><Search size={18}/><Input aria-label="Search clients" placeholder="Search clients" value={search} onChange={e=>setSearch(e.target.value)}/></div><span>{filteredClients.length} clients</span></div>
 {filteredClients.length?<div className="record-list">{filteredClients.map(c=><button className="record" key={c.id} onClick={()=>editClient(c)}><span className="client-avatar">{c.name.slice(0,1).toUpperCase()}</span><span className="record-main"><strong>{c.name}</strong><small>{c.company||c.email||c.phone||"Client details"}</small></span><span className="record-side"><small>{documents.filter(d=>d.clientId===c.id).length} documents</small></span><ChevronRight size={17}/></button>)}</div>:<Empty title={search?"No matching clients":"No clients yet"} detail={search?"Try a different search.":"Add a client to use their details in estimates and invoices."} action={!search?<Button onClick={()=>editClient()}><Plus size={17}/> Add client</Button>:undefined}/>}
 </>:view==="client"&&client?<>
 <div className="editor-head"><button className="back-link" onClick={()=>go("clients")}><ArrowLeft size={18}/> Clients</button><h1>{client.id?"Edit client":"New client"}</h1><p>These details can be selected on future documents.</p></div>
 <div className="editor-grid"><section className="panel"><h2>Contact details</h2><div className="form-grid"><Field label="Client name *"><Input value={client.name} onChange={e=>setClient({...client,name:e.target.value})} placeholder="Full name or contact"/></Field><Field label="Company"><Input value={client.company} onChange={e=>setClient({...client,company:e.target.value})}/></Field><Field label="Email"><Input type="email" value={client.email} onChange={e=>setClient({...client,email:e.target.value})}/></Field><Field label="Phone"><Input type="tel" value={client.phone} onChange={e=>setClient({...client,phone:e.target.value})}/></Field></div></section><section className="panel"><h2>Addresses & notes</h2><Field label="Billing address"><Textarea value={client.billingAddress} onChange={e=>setClient({...client,billingAddress:e.target.value})}/></Field><Field label="Job site address"><Textarea value={client.siteAddress} onChange={e=>setClient({...client,siteAddress:e.target.value})}/></Field><Field label="Internal notes"><Textarea value={client.notes} onChange={e=>setClient({...client,notes:e.target.value})}/></Field></section></div>
 <div className="editor-actions"><Button className="primary-button" disabled={saving} onClick={saveClient}><Check size={18}/>{saving?"Saving…":"Save client"}</Button>{client.id&&<Button variant="outline" className="delete-button" onClick={removeClient}><Trash2 size={17}/> Delete</Button>}</div>
 </>:view==="document"&&doc?<DocEditor doc={doc} clients={clients} photos={photos} saving={saving} back={()=>go(doc.kind==="invoice"?"invoices":"estimates")} change={setDoc} save={saveDoc} remove={removeDoc} duplicate={duplicate} print={()=>print(doc)} upload={upload} deletePhoto={deletePhoto}/>:view==="settings"?<>
 <div className="page-heading"><div><div className="eyebrow">PREFERENCES</div><h1>Business details</h1><p>Shown on documents you share with clients.</p></div></div><div className="settings-layout"><section className="panel"><h2>Your business</h2><div className="form-grid"><Field label="Business name"><Input value={business.businessName} onChange={e=>setBusiness({...business,businessName:e.target.value})}/></Field><Field label="Email"><Input type="email" value={business.email} onChange={e=>setBusiness({...business,email:e.target.value})}/></Field><Field label="Phone"><Input type="tel" value={business.phone} onChange={e=>setBusiness({...business,phone:e.target.value})}/></Field><Field label="Tax registration number"><Input value={business.taxNumber} onChange={e=>setBusiness({...business,taxNumber:e.target.value})}/></Field></div><Field label="Business address"><Textarea value={business.address} onChange={e=>setBusiness({...business,address:e.target.value})}/></Field><Field label="Default province"><NativeSelect className="select-full" value={business.province} onChange={e=>setBusiness({...business,province:e.target.value})}>{Object.entries(provinces).map(([code,v])=><NativeSelectOption key={code} value={code}>{v[0]}</NativeSelectOption>)}</NativeSelect></Field></section><section className="panel"><h2>Document defaults</h2><Field label="Default terms"><Textarea value={business.defaultTerms} onChange={e=>setBusiness({...business,defaultTerms:e.target.value})}/></Field><Field label="Payment instructions"><Textarea value={business.paymentInstructions} onChange={e=>setBusiness({...business,paymentInstructions:e.target.value})}/></Field><Button className="primary-button" disabled={saving} onClick={saveBusiness}><Check size={17}/>{saving?"Saving…":"Save business details"}</Button></section><section className="panel"><h2>Your data</h2><p className="panel-copy">Download a copy of clients, documents, and settings. Photos remain in the app.</p><Button variant="outline" onClick={backup}><Download size={17}/> Download data backup</Button></section></div>
 </>:null}</div></main><nav className="mobile-nav" aria-label="Mobile navigation">{nav.map(([v,Icon,label])=><button key={v} className={view===v?"active":""} onClick={()=>go(v)}><Icon size={21}/><span>{v==="home"?"Home":label}</span></button>)}</nav></div>
 {printDoc&&<PrintSheet doc={printDoc} client={clients.find(c=>c.id===printDoc.clientId)||printDoc.clientSnapshot} business={business} photos={photos.filter(p=>p.documentId===printDoc.id)}/>}</>
}




