"use client";
import {useRef} from "react";
import {Check,ImagePlus,LockKeyhole,LogOut,Palette,Trash2,UserRound} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {NativeSelect,NativeSelectOption} from "@/components/ui/native-select";
import {Business,Features,Profile,provinces} from "@/lib/model";
import {Field} from "@/components/doc-editor";
export function ProfilePage({profile,email,fullName,save,change,busy}:{profile:Profile;email:string;fullName:string;save:()=>void;change:(p:Profile)=>void;busy:boolean}){
 const set=<K extends keyof Profile>(key:K,value:Profile[K])=>change({...profile,[key]:value});
 return <><div className="page-heading"><div><div className="eyebrow">YOUR ACCOUNT</div><h1>Profile & security</h1><p>Your identity and signature on every client handoff.</p></div></div><div className="settings-layout"><section className="panel identity-panel"><div className="identity-avatar"><UserRound size={28}/></div><div><strong>{profile.displayName||fullName||"Your account"}</strong><span>{email}</span><small><LockKeyhole size={14}/> Secured with ChatGPT sign-in</small></div></section><section className="panel"><h2>Professional profile</h2><div className="form-grid"><Field label="Display name"><Input value={profile.displayName} onChange={e=>set("displayName",e.target.value)} placeholder={fullName||"Your name"}/></Field><Field label="Job title"><Input value={profile.jobTitle} onChange={e=>set("jobTitle",e.target.value)} placeholder="e.g. Project Manager"/></Field><Field label="Direct phone"><Input type="tel" value={profile.phone} onChange={e=>set("phone",e.target.value)} placeholder="+1 (___) ___-____"/></Field></div><Field label="Email signature" hint="Added to new client email drafts when enabled in company preferences."><Textarea value={profile.signature} onChange={e=>set("signature",e.target.value)} placeholder="Your name | Company | Phone"/></Field><Button className="primary-button" disabled={busy} onClick={save}><Check size={17}/>{busy?"Saving…":"Save profile"}</Button></section><section className="panel"><h2>Account access</h2><p className="panel-copy">Your estimates, clients, catalogue, and company profile are stored under this signed-in account. Other users have separate private records.</p><a className="signout-link" href="/signout-with-chatgpt?return_to=/" target="_top"><LogOut size={17}/> Sign out</a></section></div></>
}
export function CompanyPage({company,change,save,uploadLogo,removeLogo,busy}:{company:Business;change:(b:Business)=>void;save:()=>void;uploadLogo:(file?:File)=>void;removeLogo:()=>void;busy:boolean}){
 const logo=useRef<HTMLInputElement>(null);
 const set=<K extends keyof Business>(key:K,value:Business[K])=>change({...company,[key]:value});
 const flag=(key:keyof Features,value:boolean)=>change({...company,features:{...company.features,[key]:value}});
 const switches:[keyof Features,string,string][]=[["photos","Job photos","Include attached photos in PDFs"],["discounts","Discount field","Show discount controls in the editor"],["deposits","Deposits & payments","Show deposit or paid-to-date controls"],["taxNumber","Tax number","Print registration number"],["signature","Prepared by","Include your profile signature on PDFs"],["paymentInstructions","Payment instructions","Print payment details on invoices"],["jobAddress","Job site address","Show job location on PDFs"]];
 return <><div className="page-heading"><div><div className="eyebrow">YOUR COMPANY</div><h1>Company profile</h1><p>Make every estimate and invoice feel unmistakably yours.</p></div><Button className="primary-button" disabled={busy} onClick={save}><Check size={17}/> Save changes</Button></div><div className="company-grid"><div>
 <section className="panel"><div className="panel-heading"><h2>Identity</h2><span>01</span></div><div className="logo-upload"><div className="logo-preview">{company.logoKey?<img src={"/api/company-logo?v="+encodeURIComponent(company.logoKey)} alt="Company logo"/>:<span>GT</span>}</div><div><strong>Company logo</strong><p>PNG, JPEG, or WebP, up to 4 MB. Appears on PDFs.</p><div className="photo-actions"><Button variant="outline" onClick={()=>logo.current?.click()}><ImagePlus size={17}/> Upload logo</Button>{company.logoKey&&<Button variant="outline" onClick={removeLogo}><Trash2 size={16}/> Remove</Button>}</div></div><input ref={logo} className="visually-hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{uploadLogo(e.target.files?.[0]);e.target.value=""}}/></div>
 <div className="form-grid"><Field label="Company name"><Input value={company.businessName} onChange={e=>set("businessName",e.target.value)}/></Field><Field label="Business email"><Input type="email" value={company.email} onChange={e=>set("email",e.target.value)}/></Field><Field label="Phone"><Input type="tel" value={company.phone} onChange={e=>set("phone",e.target.value)}/></Field><Field label="Tax registration number"><Input value={company.taxNumber} onChange={e=>set("taxNumber",e.target.value)}/></Field></div><Field label="Address"><Textarea value={company.address} onChange={e=>set("address",e.target.value)}/></Field><Field label="Default province"><NativeSelect className="select-full" value={company.province} onChange={e=>set("province",e.target.value)}>{Object.entries(provinces).map(([code,v])=><NativeSelectOption key={code} value={code}>{v[0]}</NativeSelectOption>)}</NativeSelect></Field></section>
 <section className="panel"><div className="panel-heading"><h2>Documents & communication</h2><span>02</span></div><div className="form-grid"><Field label="Estimate prefix"><Input value={company.estimatePrefix} onChange={e=>set("estimatePrefix",e.target.value)} maxLength={12}/></Field><Field label="Invoice prefix"><Input value={company.invoicePrefix} onChange={e=>set("invoicePrefix",e.target.value)} maxLength={12}/></Field></div><Field label="Default terms"><Textarea value={company.defaultTerms} onChange={e=>set("defaultTerms",e.target.value)}/></Field><Field label="Payment instructions"><Textarea value={company.paymentInstructions} onChange={e=>set("paymentInstructions",e.target.value)}/></Field><Field label="PDF footer"><Input value={company.footerText} onChange={e=>set("footerText",e.target.value)} placeholder="Thank you for your business"/></Field><Field label="Email subject template" hint="Use {number}, {client}, {company}, or {total}."><Input value={company.emailSubject} onChange={e=>set("emailSubject",e.target.value)} placeholder="{company} {kind} {number}"/></Field><Field label="Email message template"><Textarea value={company.emailMessage} onChange={e=>set("emailMessage",e.target.value)} placeholder="Hello {client},&#10;&#10;Please find your {kind} attached."/></Field></section></div>
 <div><section className="panel brand-panel"><div className="panel-heading"><h2>Brand & layout</h2><Palette size={20}/></div><div className="brand-swatch" style={{background:company.accentColor,borderColor:company.secondaryColor}}><strong>{company.businessName||"Your company"}</strong><span>ESTIMATE · PREVIEW</span></div><div className="form-grid"><Field label="Primary colour"><div className="color-field"><input aria-label="Choose primary colour" type="color" value={company.accentColor} onChange={e=>set("accentColor",e.target.value)}/><Input value={company.accentColor} onChange={e=>set("accentColor",e.target.value)}/></div></Field><Field label="Accent colour"><div className="color-field"><input aria-label="Choose accent colour" type="color" value={company.secondaryColor} onChange={e=>set("secondaryColor",e.target.value)}/><Input value={company.secondaryColor} onChange={e=>set("secondaryColor",e.target.value)}/></div></Field></div><Field label="PDF layout"><NativeSelect className="select-full" value={company.documentStyle} onChange={e=>set("documentStyle",e.target.value as Business["documentStyle"])}><NativeSelectOption value="classic">Classic · crisp heading</NativeSelectOption><NativeSelectOption value="modern">Modern · bold colour band</NativeSelectOption><NativeSelectOption value="minimal">Minimal · quiet detail</NativeSelectOption></NativeSelect></Field></section>
 <section className="panel"><h2>Optional features</h2><p className="panel-copy">Keep the workspace focused on the details your team uses.</p><div className="feature-list">{switches.map(([key,title,detail])=><label key={key} className="feature-toggle"><span><strong>{title}</strong><small>{detail}</small></span><input type="checkbox" checked={company.features[key]} onChange={e=>flag(key,e.target.checked)}/></label>)}</div></section><section className="panel"><h2>Your data</h2><p className="panel-copy">Every signed-in user has private records. Save your company changes before creating new documents so defaults carry through.</p></section></div></div></>
}

