"use client";
import {useState} from "react";
import {ArrowRight,Eye,EyeOff,LockKeyhole,ShieldCheck} from "lucide-react";
import {Input} from "@/components/ui/input";
import {Button} from "@/components/ui/button";
type Mode="login"|"register";
const errors:Record<string,string>={"google-state":"Google sign-in expired. Please try again.","google-config":"Google sign-in is not configured yet.","google-token":"Google sign-in could not be completed.","google-profile":"Could not read your Google profile.","google-email":"Google did not confirm a verified email address.","existing-email":"This email is already registered. Sign in with its original method.","google-failed":"Google sign-in failed. Please try again."};
export default function AuthScreen({mode,googleEnabled,chatgptAvailable,initialError}:{mode:Mode;googleEnabled:boolean;chatgptAvailable:boolean;initialError?:string}){
 const [name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(errors[initialError||""]||"");
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/auth/"+mode,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,password})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"Please try again.");window.location.assign("/")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="auth-layout"><div className="auth-left"><a href="/" className="auth-logo"><span>GT</span><strong>GRAND TERRA <em>ESTIMATES</em></strong></a><div className="auth-story"><div className="eyebrow">BUILT FOR CONTRACTORS</div><h1>Every project starts with a clear number.</h1><p>Send polished estimates, stay on top of invoices, and keep every client detail in one secure workspace.</p><div className="auth-trust"><ShieldCheck size={19}/> Private records for every account</div></div><div className="auth-footer">© Grand Terra Group of Companies</div></div><div className="auth-right"><div className="auth-form-card"><div className="eyebrow">YOUR WORKSPACE</div><h2>{mode==="register"?"Create your account":"Welcome back"}</h2><p>{mode==="register"?"Start with a secure account and make the workspace your own.":"Pick up exactly where you left off."}</p>{error&&<div className="auth-error" role="alert">{error}</div>}<form onSubmit={submit}>{mode==="register"&&<label>Full name<Input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} required minLength={2}/></label>}<label>Email address<Input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<div className="password-field"><Input type={show?"text":"password"} autoComplete={mode==="register"?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)} required minLength={mode==="register"?12:1}/><button type="button" aria-label={show?"Hide password":"Show password"} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{mode==="register"&&<small className="auth-hint">Use at least 12 characters. Your device stays signed in until you sign out or the session expires. Keep this password safe: email-based recovery is not configured yet.</small>}<Button className="auth-submit" type="submit" disabled={busy}>{busy?"Please wait…":mode==="register"?"Create account":"Sign in"}<ArrowRight size={18}/></Button></form>{(googleEnabled||chatgptAvailable)&&<div className="auth-divider"><span>or continue with</span></div>}{googleEnabled&&<a className="auth-provider" href="/api/auth/google/start"><span className="google-g">G</span> Google</a>}{chatgptAvailable&&<a className="auth-provider" href="/signin-with-chatgpt?return_to=%2F" target="_top"><LockKeyhole size={18}/> ChatGPT</a>}<div className="auth-switch">{mode==="register"?<>Already have an account? <a href="/login">Sign in</a></>:<>New to Grand Terra Estimates? <a href="/register">Create an account</a></>}</div><a className="auth-home" href="/">← Back to overview</a></div></div></main>
}

