"use client";
import {useState} from "react";
import {Box,Check,Package,Plus,Search,Trash2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {NativeSelect,NativeSelectOption} from "@/components/ui/native-select";
import {CatalogEntry,Item,blankCatalog,cash,cents,dollars,item} from "@/lib/model";
import {Field,MoneyInput,UnitPicker} from "@/components/doc-editor";
export default function CatalogPage({entries,onSave,onDelete,busy}:{entries:CatalogEntry[];onSave:(entry:CatalogEntry)=>Promise<boolean>;onDelete:(entry:CatalogEntry)=>Promise<void>;busy:boolean}){
 const [kind,setKind]=useState<"item"|"package">("item"),[search,setSearch]=useState(""),[editing,setEditing]=useState<CatalogEntry|null>(null);
 const shown=entries.filter(e=>e.kind===kind&&(e.name+" "+e.description).toLowerCase().includes(search.toLowerCase()));
 const update=<K extends keyof CatalogEntry>(key:K,value:CatalogEntry[K])=>setEditing(e=>e?{...e,[key]:value}:e);
 const line=(id:string,patch:Partial<Item>)=>setEditing(e=>e?{...e,items:e.items.map(i=>i.id===id?{...i,...patch}:i)}:e);
 async function save(){if(editing&&await onSave(editing))setEditing(null)}
 return <><div className="page-heading"><div><div className="eyebrow">YOUR LIBRARY</div><h1>Items & packages</h1><p>Build estimates and invoices from the work you quote most often.</p></div><Button className="primary-button" onClick={()=>setEditing(blankCatalog(kind))}><Plus size={18}/> New {kind}</Button></div>
 <div className="segment-control"><button className={kind==="item"?"active":""} onClick={()=>{setKind("item");setEditing(null)}}><Box size={17}/> Items <span>{entries.filter(e=>e.kind==="item").length}</span></button><button className={kind==="package"?"active":""} onClick={()=>{setKind("package");setEditing(null)}}><Package size={17}/> Packages <span>{entries.filter(e=>e.kind==="package").length}</span></button></div>
 {editing?<div className="catalog-editor"><div className="catalog-editor-head"><div><div className="eyebrow">{editing.id?"EDIT":"NEW"} {editing.kind.toUpperCase()}</div><h2>{editing.kind==="item"?"Reusable item":"Reusable package"}</h2></div><Button variant="outline" onClick={()=>setEditing(null)}>Close</Button></div>
 <div className="form-grid"><Field label="Name *"><Input value={editing.name} onChange={e=>update("name",e.target.value)} placeholder={editing.kind==="item"?"e.g. Drywall installation":"e.g. Bathroom refresh"}/></Field>{editing.kind==="item"?<Field label="Unit"><UnitPicker value={editing.unit} onChange={v=>update("unit",v)}/></Field>:<div/>}</div>
 <Field label="Description"><Textarea value={editing.description} onChange={e=>update("description",e.target.value)} placeholder="What this includes or when to use it"/></Field>
 {editing.kind==="item"?<div className="form-grid"><Field label="Default unit price (CAD)"><MoneyInput value={editing.unitPriceCents} onChange={v=>update("unitPriceCents",v)}/></Field><label className="checkline catalog-tax"><input type="checkbox" checked={editing.taxable} onChange={e=>update("taxable",e.target.checked)}/> Taxable by default</label></div>:<div><div className="section-head"><h3>Package lines</h3><span>{editing.items.length} items</span></div>{editing.items.map((i,n)=><div className="catalog-line" key={i.id}><div className="line-top"><strong>Line {n+1}</strong><button aria-label="Remove line" onClick={()=>update("items",editing.items.filter(x=>x.id!==i.id))}><Trash2 size={17}/></button></div><Field label="Description"><Input value={i.description} onChange={e=>line(i.id,{description:e.target.value})}/></Field><div className="catalog-line-grid"><Field label="Quantity"><Input type="number" min="0" step=".01" value={i.quantity} onChange={e=>line(i.id,{quantity:Number(e.target.value)||0})}/></Field><Field label="Unit"><UnitPicker value={i.unit} onChange={v=>line(i.id,{unit:v})}/></Field><Field label="Unit price"><MoneyInput value={i.unitPriceCents} onChange={v=>line(i.id,{unitPriceCents:v})}/></Field></div><label className="checkline"><input type="checkbox" checked={i.taxable} onChange={e=>line(i.id,{taxable:e.target.checked})}/> Taxable</label></div>)}<Button variant="outline" onClick={()=>update("items",[...editing.items,item()])}><Plus size={16}/> Add package line</Button></div>}
 <div className="editor-actions"><Button className="primary-button" disabled={busy} onClick={save}><Check size={17}/>{busy?"Saving…":"Save "+editing.kind}</Button>{editing.id&&<Button variant="outline" className="delete-button" disabled={busy} onClick={async()=>{await onDelete(editing);setEditing(null)}}><Trash2 size={17}/> Delete</Button>}</div></div>:<><div className="toolbar"><div className="search"><Search size={18}/><Input aria-label={"Search "+kind+"s"} placeholder={"Search "+kind+"s"} value={search} onChange={e=>setSearch(e.target.value)}/></div><span>{shown.length} saved</span></div>{shown.length?<div className="catalog-grid">{shown.map(e=><button key={e.id} className="catalog-card" onClick={()=>setEditing({...e,items:e.items.map(i=>({...i}))})}><span className="catalog-card-icon">{e.kind==="package"?<Package size={21}/>:<Box size={21}/>}</span><strong>{e.name}</strong><small>{e.description|| (e.kind==="package"?e.items.length+" lines":e.unit)}</small><span>{e.kind==="package"?cash(e.items.reduce((s,i)=>s+i.quantity*i.unitPriceCents,0)):cash(e.unitPriceCents)+" / "+e.unit}</span></button>)}</div>:<div className="empty"><div className="empty-icon">{kind==="item"?<Box size={24}/>:<Package size={24}/>}</div><h3>{search?"No matches":"No "+kind+"s saved yet"}</h3><p>{search?"Try another search.":"Save common work to make every new document faster."}</p><Button onClick={()=>setEditing(blankCatalog(kind))}><Plus size={17}/> New {kind}</Button></div>}</>}
 </>;
}

