"use client";
import { useEffect,useRef,useState } from "react";
import { ArrowLeft, Camera, Check, Copy, FileText, ImagePlus, Plus, Printer, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { NativeSelect,NativeSelectOption } from "@/components/ui/native-select";
import { Client,Doc,Item,Photo,provinces,cash,cents,dollars,item,totals } from "@/lib/model";
export function Field({label,children,hint}:{label:string;children:React.ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function MoneyInput({value,onChange}:{value:number;onChange:(cents:number)=>void}){const [text,setText]=useState(dollars(value));const ref=useRef<HTMLInputElement>(null);useEffect(()=>{if(document.activeElement!==ref.current)setText(dollars(value))},[value]);return <Input ref={ref} inputMode="decimal" type="text" value={text} onChange={e=>{setText(e.target.value);onChange(cents(e.target.value))}} onBlur={()=>setText(dollars(value))}/>}
export default function DocEditor({doc,clients,photos,saving,back,change,save,remove,duplicate,print,upload,deletePhoto}:{doc:Doc;clients:Client[];photos:Photo[];saving:boolean;back:()=>void;change:(d:Doc)=>void;save:()=>void;remove:()=>void;duplicate:(kind?:"estimate"|"invoice")=>void;print:()=>void;upload:(file?:File)=>void;deletePhoto:(p:Photo)=>void}){
 const camera=useRef<HTMLInputElement>(null),library=useRef<HTMLInputElement>(null);
 const set=<K extends keyof Doc>(key:K,value:Doc[K])=>change({...doc,[key]:value});
 const setItem=(id:string,patch:Partial<Item>)=>set("items",doc.items.map(i=>i.id===id?{...i,...patch}:i));
 const t=totals(doc),client=clients.find(c=>c.id===doc.clientId);
 return <><div className="editor-head"><button className="back-link" onClick={back}><ArrowLeft size={18}/>{doc.kind==="invoice"?"Invoices":"Estimates"}</button><div className="eyebrow">{doc.id?"EDIT DOCUMENT":"NEW DOCUMENT"}</div><h1>{doc.kind==="invoice"?"Invoice":"Estimate"} {doc.number}</h1></div>
 <div className="editor-grid"><div className="editor-main">
 <section className="panel"><div className="panel-heading"><h2>Project & client</h2><span>01</span></div><div className="form-grid">
 <Field label="Client *"><NativeSelect className="select-full" value={doc.clientId||""} onChange={e=>set("clientId",e.target.value||null)}><NativeSelectOption value="">Select a client</NativeSelectOption>{clients.map(c=><NativeSelectOption key={c.id} value={c.id}>{c.name}{c.company?" — "+c.company:""}</NativeSelectOption>)}</NativeSelect>{clients.length===0&&<small>Add a client in the Clients tab first.</small>}</Field>
 <Field label="Project title"><Input value={doc.title} onChange={e=>set("title",e.target.value)} placeholder="e.g. Kitchen renovation"/></Field>
 <Field label="Document number"><Input value={doc.number} onChange={e=>set("number",e.target.value)}/></Field>
 <Field label="Status"><NativeSelect className="select-full" value={doc.status} onChange={e=>set("status",e.target.value)}>{(doc.kind==="invoice"?["draft","sent","partial","paid","overdue"]:["draft","sent","accepted","declined"]).map(s=><NativeSelectOption key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</NativeSelectOption>)}</NativeSelect></Field>
 <Field label="Issue date"><Input type="date" value={doc.issueDate} onChange={e=>set("issueDate",e.target.value)}/></Field>
 <Field label={doc.kind==="invoice"?"Due date":"Valid until"}><Input type="date" value={doc.dueDate} onChange={e=>set("dueDate",e.target.value)}/></Field></div>
 {client&&<div className="client-preview"><strong>{client.name}</strong><span>{client.company}</span><span>{client.email}{client.phone?" · "+client.phone:""}</span><span>{client.siteAddress||client.billingAddress}</span></div>}</section>
 <section className="panel"><div className="panel-heading"><h2>Line items</h2><span>02</span></div><div className="line-items">{doc.items.map((i,index)=><div className="line-item" key={i.id}><div className="line-top"><strong>Item {index+1}</strong><button aria-label={"Remove item "+(index+1)} onClick={()=>set("items",doc.items.filter(x=>x.id!==i.id))}><Trash2 size={17}/></button></div>
 <Field label="Description"><Input value={i.description} onChange={e=>setItem(i.id,{description:e.target.value})} placeholder="Work, material, or service"/></Field>
 <div className="item-fields"><Field label="Quantity"><Input type="number" min="0" step="0.01" value={i.quantity} onChange={e=>setItem(i.id,{quantity:Number(e.target.value)||0})}/></Field><Field label="Unit"><Input value={i.unit} onChange={e=>setItem(i.id,{unit:e.target.value})}/></Field><Field label="Unit price (CAD)"><MoneyInput value={i.unitPriceCents} onChange={v=>setItem(i.id,{unitPriceCents:v})}/></Field></div>
 <div className="line-bottom"><label className="checkline"><input type="checkbox" checked={i.taxable} onChange={e=>setItem(i.id,{taxable:e.target.checked})}/> Taxable</label><strong>{cash(Math.round(i.quantity*i.unitPriceCents))}</strong></div></div>)}</div><Button variant="outline" className="add-line" onClick={()=>set("items",[...doc.items,item()])}><Plus size={17}/> Add line item</Button></section>
 <section className="panel"><div className="panel-heading"><h2>Notes & terms</h2><span>03</span></div><Field label="Message to client"><Textarea value={doc.notes} onChange={e=>set("notes",e.target.value)} placeholder="Scope details or a thank-you note"/></Field><Field label="Terms"><Textarea value={doc.terms} onChange={e=>set("terms",e.target.value)} placeholder="Payment terms, exclusions, or validity"/></Field></section>
 <section className="panel"><div className="panel-heading"><h2>Job photos</h2><span>04</span></div><p className="panel-copy">Attach site conditions, progress photos, or reference images. Save this document first.</p><div className="photo-actions"><Button variant="outline" disabled={!doc.id||saving} onClick={()=>camera.current?.click()}><Camera size={17}/> Take photo</Button><Button variant="outline" disabled={!doc.id||saving} onClick={()=>library.current?.click()}><ImagePlus size={17}/> Add from device</Button></div><input ref={camera} className="visually-hidden" type="file" accept="image/*" capture="environment" onChange={e=>{upload(e.target.files?.[0]);e.target.value=""}}/><input ref={library} className="visually-hidden" type="file" accept="image/*" onChange={e=>{upload(e.target.files?.[0]);e.target.value=""}}/><div className="photo-grid">{photos.filter(p=>p.documentId===doc.id).map(p=><div className="photo" key={p.id}><img src={"/api/photos?id="+encodeURIComponent(p.id)} alt={p.filename}/><button aria-label={"Delete "+p.filename} onClick={()=>deletePhoto(p)}><X size={15}/></button></div>)}</div></section></div>
 <aside className="editor-side"><section className="panel totals-panel"><h2>Pricing</h2><Field label="Province / territory"><NativeSelect className="select-full" value={doc.province} onChange={e=>{const code=e.target.value;change({...doc,province:code,taxRate:provinces[code]?.[1]??5000})}}>{Object.entries(provinces).map(([code,v])=><NativeSelectOption key={code} value={code}>{v[0]}</NativeSelectOption>)}</NativeSelect></Field><Field label="Tax rate (%)" hint="Suggested GST/HST rate. Confirm any PST/QST or job-specific treatment."><Input type="number" min="0" max="30" step="0.001" value={doc.taxRate/1000} onChange={e=>set("taxRate",Math.round((Number(e.target.value)||0)*1000))}/></Field><Field label="Discount (CAD)"><MoneyInput value={doc.discountCents} onChange={v=>set("discountCents",v)}/></Field><Field label={doc.kind==="invoice"?"Paid to date (CAD)":"Deposit requested (CAD)"}><MoneyInput value={doc.depositCents} onChange={v=>set("depositCents",v)}/></Field><div className="total-rows"><div><span>Subtotal</span><strong>{cash(t.subtotal)}</strong></div>{doc.discountCents>0&&<div><span>Discount</span><strong>−{cash(doc.discountCents)}</strong></div>}{t.gst>0?<><div><span>GST (5%)</span><strong>{cash(t.gst)}</strong></div><div><span>QST (9.975%)</span><strong>{cash(t.qst)}</strong></div></>:<div><span>Tax ({doc.taxRate/1000}%)</span><strong>{cash(t.tax)}</strong></div>}<div className="grand-total"><span>Total CAD</span><strong>{cash(t.total)}</strong></div>{doc.depositCents>0&&<div><span>{doc.kind==="invoice"?"Balance due":"After deposit"}</span><strong>{cash(t.balance)}</strong></div>}</div><Button className="primary-button save-wide" disabled={saving} onClick={save}><Check size={17}/>{saving?"Saving…":"Save "+doc.kind}</Button><Button variant="outline" className="save-wide" onClick={print}><Printer size={17}/> Print / save PDF</Button></section>{doc.id&&<div className="document-tools"><button onClick={()=>duplicate()}><Copy size={17}/> Duplicate</button>{doc.kind==="estimate"&&<button onClick={()=>duplicate("invoice")}><FileText size={17}/> Create invoice from estimate</button>}<button className="danger-link" onClick={remove}><Trash2 size={17}/> Delete document</button></div>}</aside></div></>
}




