"use client";
import {useEffect,useState} from "react";
import {ArrowLeft,BookOpen,Check,ChevronRight,ClipboardList,Download,FileText,Home,Plus,Search,Settings,Trash2,UserRound,Users,X} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import DocEditor,{Field} from "@/components/doc-editor";
import CatalogPage from "@/components/catalog-page";
import {CompanyPage,ProfilePage} from "@/components/account-pages";
import EmailComposer from "@/components/email-composer";
import PdfPreview from "@/components/pdf-preview";
import {logoFile} from "@/lib/logo";
import {Business,CatalogEntry,Client,Doc,Photo,Profile,blankBusiness,blankClient,blankDoc,blankProfile,cash,today,totals,readBusiness,readCatalog,readClient,readDoc,readProfile,mutate} from "@/lib/model";
import {downloadPdf,makePdf} from "@/lib/pdf";
type View="home"|"estimates"|"invoices"|"clients"|"catalog"|"profile"|"company"|"more"|"client"|"document";
function Status({value}:{value:string}){return <span className={"status status-"+value}>{value}</span>}
function Empty({title,detail,action}:{title:string;detail:string;action?:React.ReactNode}){return <div className="empty"><div className="empty-icon"><ClipboardList size={25}/></div><h3>{title}</h3><p>{detail}</p>{action}</div>}
export default function Workspace(){
 const [view,setView]=useState<View>("home"),[clients,setClients]=useState<Client[]>([]),[documents,setDocuments]=useState<Doc[]>([]),[photos,setPhotos]=useState<Photo[]>([]),[catalog,setCatalog]=useState<CatalogEntry[]>([]);
 const [business,setBusiness]=useState<Business>(blankBusiness),[profile,setProfile]=useState<Profile>(blankProfile),[auth,setAuth]=useState<{email:string;fullName:string;provider:"account"|"chatgpt"}>({email:"",fullName:"",provider:"account"}),[client,setClient]=useState<Client|null>(null),[doc,setDoc]=useState<Doc|null>(null),[emailDoc,setEmailDoc]=useState<Doc|null>(null),[previewDoc,setPreviewDoc]=useState<Doc|null>(null);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[search,setSearch]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function refresh(){const response=await fetch("/api/data",{cache:"no-store"});const data=await response.json() as {error?:string;clients?:Record<string,unknown>[];documents?:Record<string,unknown>[];photos?:Record<string,unknown>[];catalog?:Record<string,unknown>[];settings:Record<string,unknown>|null;profile:Record<string,unknown>|null;auth?:{email:string;fullName:string;provider:"account"|"chatgpt"}};if(!response.ok)throw new Error(data.error||"Could not load data.");setClients((data.clients||[]).map(readClient));setDocuments((data.documents||[]).map(readDoc));setPhotos((data.photos||[]).map(p=>({id:String(p.id),documentId:String(p.document_id),filename:String(p.filename)})));setCatalog((data.catalog||[]).map(readCatalog));setBusiness(readBusiness(data.settings));setProfile(readProfile(data.profile));setAuth(data.auth||{email:"",fullName:"",provider:"account"})}
 useEffect(()=>{refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:()=>{view:string}};const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();for(const [name,title,target] of [["open_estimates","Open estimates","estimates"],["open_clients","Open clients","clients"],["open_catalog","Open catalogue","catalog"]] as const){void Promise.resolve(context.registerTool({name,title,description:"Open the "+target+" view in Grand Terra Estimates.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>{setView(target);return{view:target}}},{signal:controller.signal})).catch(console.error)}return()=>controller.abort()},[]);
 function flash(s:string){setNotice(s);setTimeout(()=>setNotice(""),4000)}
 function go(v:View){setView(v);setSearch("");setError("");window.scrollTo({top:0,behavior:"smooth"})}
 function editClient(c?:Client){setClient(c?{...c}:blankClient());go("client")}
 function editDoc(d?:Doc,kind:"estimate"|"invoice"="estimate"){setDoc(d?{...d,items:d.items.map(i=>({...i}))}:blankDoc(kind,business));go("document")}
 async function saveClient(){if(!client?.name.trim()){setError("Enter a client name.");return}setSaving(true);setError("");try{await mutate("saveClient",client,client.id);await refresh();flash("Client saved");go("clients")}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function saveDoc(){if(!doc?.clientId){setError("Select a saved client.");return}const selected=clients.find(c=>c.id===doc.clientId);if(!selected){setError("Select a saved client.");return}setSaving(true);setError("");try{const value={...doc,clientSnapshot:selected};const result=await mutate("saveDocument",value,doc.id);setDoc({...value,id:String(result.id||"")});await refresh();flash("Document saved")}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function saveBusiness(){setSaving(true);setError("");try{await mutate("saveSettings",business);flash("Company profile saved")}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function saveProfile(){setSaving(true);setError("");try{await mutate("saveProfile",profile);flash("Profile saved")}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function saveCatalog(entry:CatalogEntry){setSaving(true);setError("");try{await mutate("saveCatalog",entry,entry.id);await refresh();flash((entry.kind==="package"?"Package":"Item")+" saved to catalogue");return true}catch(e){setError((e as Error).message);return false}finally{setSaving(false)}}
 async function saveLine(line:Doc["items"][number]){await saveCatalog({id:"",kind:"item",name:line.description,description:"",unit:line.unit,unitPriceCents:line.unitPriceCents,taxable:line.taxable,items:[],updatedAt:0})}
 async function removeCatalog(entry:CatalogEntry){if(!confirm("Delete "+entry.name+" from your catalogue?"))return;try{await mutate("deleteCatalog",{},entry.id);await refresh();flash("Catalogue entry deleted")}catch(e){setError((e as Error).message)}}
 async function removeClient(){if(!client||!confirm("Delete this client? Saved documents keep a copy of the client details."))return;try{await mutate("deleteClient",{},client.id);await refresh();go("clients");flash("Client deleted")}catch(e){setError((e as Error).message)}}
 async function removeDoc(){if(!doc||!confirm("Permanently delete this document and its photos?"))return;try{await mutate("deleteDocument",{},doc.id);await refresh();go(doc.kind==="invoice"?"invoices":"estimates");flash("Document deleted")}catch(e){setError((e as Error).message)}}
 async function upload(file?:File){if(!file||!doc?.id)return;setSaving(true);setError("");try{const form=new FormData();form.append("documentId",doc.id);form.append("file",file);const response=await fetch("/api/photos",{method:"POST",body:form});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"Upload failed");await refresh();flash("Photo added")}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function deletePhoto(p:Photo){if(!confirm("Delete this photo?"))return;try{const response=await fetch("/api/photos?id="+encodeURIComponent(p.id),{method:"DELETE"});if(!response.ok)throw new Error("Could not delete photo.");await refresh();flash("Photo deleted")}catch(e){setError((e as Error).message)}}
 async function uploadLogo(file?:File){if(!file)return;setSaving(true);setError("");try{const form=new FormData();form.append("file",await logoFile(file));const response=await fetch("/api/company-logo",{method:"POST",body:form});const data=await response.json() as {error?:string;logoKey?:string};if(!response.ok)throw new Error(data.error||"Logo upload failed");setBusiness(b=>({...b,logoKey:data.logoKey||""}));flash("Logo updated")}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function removeLogo(){try{const response=await fetch("/api/company-logo",{method:"DELETE"});if(!response.ok)throw new Error("Could not remove logo.");setBusiness(b=>({...b,logoKey:""}));flash("Logo removed")}catch(e){setError((e as Error).message)}}
 function duplicate(kind?:"estimate"|"invoice"){if(!doc)return;const k=kind||doc.kind;setDoc({...doc,id:"",kind:k,number:(k==="invoice"?business.invoicePrefix:business.estimatePrefix)+"-"+new Date().getFullYear()+"-"+String(Date.now()).slice(-5),status:"draft",issueDate:today(),dueDate:"",depositCents:0,items:doc.items.map(i=>({...i,id:crypto.randomUUID()}))});window.scrollTo({top:0,behavior:"smooth"})}
 async function exportPdf(d:Doc){setError("");try{const file=await makePdf(d,clients.find(c=>c.id===d.clientId)||d.clientSnapshot,business,profile,photos.filter(p=>p.documentId===d.id));downloadPdf(file);flash("PDF downloaded")}catch(e){setError("PDF could not be created: "+(e as Error).message)}}
 async function signOut(){if(auth.provider==="chatgpt"){window.location.assign("/signout-with-chatgpt?return_to=%2Flogin");return}try{await fetch("/api/auth/logout",{method:"POST"});window.location.assign("/login")}catch{setError("Could not sign out. Please try again.")}}
 function backup(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),clients,documents,catalog,business,profile},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="grand-terra-backup-"+today()+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 const kind=view==="invoices"?"invoice":"estimate";
 const filteredDocs=documents.filter(d=>d.kind===kind&&(d.number+" "+d.title+" "+(clients.find(c=>c.id===d.clientId)?.name||d.clientSnapshot.name||"")).toLowerCase().includes(search.toLowerCase()));
 const filteredClients=clients.filter(c=>(c.name+" "+c.company+" "+c.email+" "+c.phone).toLowerCase().includes(search.toLowerCase()));
 const outstanding=documents.filter(d=>d.kind==="invoice"&&d.status!=="paid").reduce((s,d)=>s+totals(d).balance,0),pipeline=documents.filter(d=>d.kind==="estimate"&&["draft","sent"].includes(d.status)).reduce((s,d)=>s+totals(d).total,0);
 const nav=([["home",Home,"Overview"],["estimates",ClipboardList,"Estimates"],["invoices",FileText,"Invoices"],["clients",Users,"Clients"],["catalog",BookOpen,"Catalogue"],["profile",UserRound,"My profile"],["company",Settings,"Company"]] as const);
 const mobile=([["home",Home,"Home"],["estimates",ClipboardList,"Estimates"],["invoices",FileText,"Invoices"],["clients",Users,"Clients"],["catalog",BookOpen,"Library"],["more",Settings,"More"]] as const);
 const title=view==="document"?(doc?.kind==="invoice"?"Invoice editor":"Estimate editor"):view==="client"?"Client details":view==="home"?"Overview":view==="catalog"?"Catalogue":view==="profile"?"My profile":view==="company"?"Company":view[0].toUpperCase()+view.slice(1);
 return <><div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">GT</div><div><strong>GRAND TERRA</strong><span>GROUP OF COMPANIES</span></div></div><nav aria-label="Main navigation">{nav.map(([v,Icon,label])=><button key={v} className={"nav-item "+(view===v?"active":"")} onClick={()=>go(v)}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="sidebar-foot"><span className="online-dot"/> Secure workspace<br/><small>{auth.email||"Grand Terra · Canada"}</small></div></aside>
 <main className="main"><header className="topbar"><div className="mobile-brand"><div className="brand-mark">GT</div><strong>GRAND TERRA</strong></div><div className="topbar-title">{title}</div><div className="topbar-actions"><span>{profile.displayName||auth.fullName||"Contractor workspace"}</span><button className="avatar avatar-button" aria-label="Open profile" onClick={()=>go("profile")}>{(profile.displayName||auth.fullName||auth.email||"GT").slice(0,2).toUpperCase()}</button></div></header><div className="content">
 {error&&<div role="alert" className="banner error"><span>{error}</span><button aria-label="Dismiss" onClick={()=>setError("")}><X size={17}/></button></div>}{notice&&<div role="status" className="banner success"><Check size={17}/>{notice}</div>}
 {loading?<div className="loading">Loading your workspace…</div>:view==="home"?<>
 <div className="overview-hero"><div><div className="eyebrow">GRAND TERRA WORKSPACE</div><h1>Ready for the next project.</h1><p>Keep every quote, invoice, and client detail moving together.</p></div><Button className="hero-button" onClick={()=>editDoc()}><Plus size={18}/> New estimate</Button></div>
 <div className="quick-actions"><button onClick={()=>editDoc()}><span className="quick-icon blue"><ClipboardList size={21}/></span><span><strong>Create estimate</strong><small>Build a quote in minutes</small></span><ChevronRight size={18}/></button><button onClick={()=>editDoc(undefined,"invoice")}><span className="quick-icon green"><FileText size={21}/></span><span><strong>Create invoice</strong><small>Bill a client or job</small></span><ChevronRight size={18}/></button><button onClick={()=>go("catalog")}><span className="quick-icon gold"><BookOpen size={21}/></span><span><strong>Use your catalogue</strong><small>{catalog.length} saved items & packages</small></span><ChevronRight size={18}/></button></div>
 <div className="stats"><div className="stat"><span>Active estimates</span><strong>{documents.filter(d=>d.kind==="estimate"&&["draft","sent"].includes(d.status)).length}</strong><small>{cash(pipeline)} in pipeline</small></div><div className="stat"><span>Outstanding invoices</span><strong>{documents.filter(d=>d.kind==="invoice"&&d.status!=="paid").length}</strong><small>{cash(outstanding)} to collect</small></div><div className="stat"><span>Saved clients</span><strong>{clients.length}</strong><small>Ready for your next job</small></div></div>
 <section className="section"><div className="section-head"><div><h2>Recent documents</h2><p>Pick up where you left off.</p></div><button className="text-action" onClick={()=>go("estimates")}>View estimates <ChevronRight size={16}/></button></div>{documents.length?<div className="record-list">{documents.slice(0,5).map(d=><button className="record" key={d.id} onClick={()=>editDoc(d)}><span className={"record-icon "+d.kind}><FileText size={21}/></span><span className="record-main"><strong>{d.title||d.number}</strong><small>{d.number} · {clients.find(c=>c.id===d.clientId)?.name||d.clientSnapshot.name||"No client"}</small></span><span className="record-side"><strong>{cash(totals(d).total)}</strong><Status value={d.status}/></span><ChevronRight size={17}/></button>)}</div>:<Empty title="No documents yet" detail="Create an estimate to start your project history." action={<Button onClick={()=>editDoc()}><Plus size={17}/> New estimate</Button>}/>}</section>
 </>:view==="estimates"||view==="invoices"?<>
 <div className="page-heading"><div><div className="eyebrow">DOCUMENTS</div><h1>{view==="invoices"?"Invoices":"Estimates"}</h1><p>{view==="invoices"?"Track billing and payments.":"Create, revise, and track client quotes."}</p></div><Button className="primary-button" onClick={()=>editDoc(undefined,kind)}><Plus size={18}/> New {kind}</Button></div>
 <div className="toolbar"><div className="search"><Search size={18}/><Input aria-label={"Search "+view} placeholder="Search client, title, or number" value={search} onChange={e=>setSearch(e.target.value)}/></div><span>{filteredDocs.length} {kind}{filteredDocs.length===1?"":"s"}</span></div>
 {filteredDocs.length?<div className="record-list">{filteredDocs.map(d=><button className="record" key={d.id} onClick={()=>editDoc(d)}><span className={"record-icon "+d.kind}><FileText size={21}/></span><span className="record-main"><strong>{d.title||d.number}</strong><small>{d.number} · {clients.find(c=>c.id===d.clientId)?.name||d.clientSnapshot.name||"No client"} · {d.issueDate}</small></span><span className="record-side"><strong>{cash(totals(d).total)}</strong><Status value={d.status}/></span><ChevronRight size={17}/></button>)}</div>:<Empty title={search?"No matching documents":"No "+view+" yet"} detail={search?"Try a different search.":"Create your first "+kind+" to get started."} action={!search?<Button onClick={()=>editDoc(undefined,kind)}><Plus size={17}/> New {kind}</Button>:undefined}/>}
 </>:view==="clients"?<>
 <div className="page-heading"><div><div className="eyebrow">CONTACTS</div><h1>Clients</h1><p>Keep contact and job addresses ready for every quote.</p></div><Button className="primary-button" onClick={()=>editClient()}><Plus size={18}/> Add client</Button></div>
 <div className="toolbar"><div className="search"><Search size={18}/><Input aria-label="Search clients" placeholder="Search clients" value={search} onChange={e=>setSearch(e.target.value)}/></div><span>{filteredClients.length} clients</span></div>
 {filteredClients.length?<div className="record-list">{filteredClients.map(c=><button className="record" key={c.id} onClick={()=>editClient(c)}><span className="client-avatar">{c.name.slice(0,1).toUpperCase()}</span><span className="record-main"><strong>{c.name}</strong><small>{c.company||c.email||c.phone||"Client details"}</small></span><span className="record-side"><small>{documents.filter(d=>d.clientId===c.id).length} documents</small></span><ChevronRight size={17}/></button>)}</div>:<Empty title={search?"No matching clients":"No clients yet"} detail={search?"Try a different search.":"Add a client to use their details in estimates and invoices."} action={!search?<Button onClick={()=>editClient()}><Plus size={17}/> Add client</Button>:undefined}/>}
 </>:view==="catalog"?<CatalogPage entries={catalog} onSave={saveCatalog} onDelete={removeCatalog} busy={saving}/>:view==="profile"?<ProfilePage profile={profile} email={auth.email} fullName={auth.fullName} provider={auth.provider} save={saveProfile} change={setProfile} signOut={signOut} busy={saving}/>:view==="company"?<CompanyPage company={business} profile={profile} change={setBusiness} save={saveBusiness} uploadLogo={uploadLogo} removeLogo={removeLogo} busy={saving}/>:view==="more"?<><div className="page-heading"><div><div className="eyebrow">WORKSPACE</div><h1>More</h1><p>Your account, company, and data.</p></div></div><div className="record-list"><button className="record" onClick={()=>go("profile")}><UserRound size={20}/><span className="record-main"><strong>My profile</strong><small>Identity, signature & security</small></span><ChevronRight size={17}/></button><button className="record" onClick={()=>go("company")}><Settings size={20}/><span className="record-main"><strong>Company</strong><small>Branding, PDFs & preferences</small></span><ChevronRight size={17}/></button><button className="record" onClick={backup}><Download size={20}/><span className="record-main"><strong>Download data backup</strong><small>Clients, documents & catalogue</small></span><ChevronRight size={17}/></button></div></>:view==="client"&&client?<>
 <div className="editor-head"><button className="back-link" onClick={()=>go("clients")}><ArrowLeft size={18}/> Clients</button><h1>{client.id?"Edit client":"New client"}</h1><p>These details can be selected on future documents.</p></div>
 <div className="editor-grid"><section className="panel"><h2>Contact details</h2><div className="form-grid"><Field label="Client name *"><Input value={client.name} onChange={e=>setClient({...client,name:e.target.value})} placeholder="Full name or contact"/></Field><Field label="Company"><Input value={client.company} onChange={e=>setClient({...client,company:e.target.value})}/></Field><Field label="Email"><Input type="email" value={client.email} onChange={e=>setClient({...client,email:e.target.value})}/></Field><Field label="Phone"><Input type="tel" value={client.phone} onChange={e=>setClient({...client,phone:e.target.value})}/></Field></div></section><section className="panel"><h2>Addresses & notes</h2><Field label="Billing address"><Textarea value={client.billingAddress} onChange={e=>setClient({...client,billingAddress:e.target.value})}/></Field><Field label="Job site address"><Textarea value={client.siteAddress} onChange={e=>setClient({...client,siteAddress:e.target.value})}/></Field><Field label="Internal notes"><Textarea value={client.notes} onChange={e=>setClient({...client,notes:e.target.value})}/></Field></section></div><div className="editor-actions"><Button className="primary-button" disabled={saving} onClick={saveClient}><Check size={18}/>{saving?"Saving…":"Save client"}</Button>{client.id&&<Button variant="outline" className="delete-button" onClick={removeClient}><Trash2 size={17}/> Delete</Button>}</div>
 </>:view==="document"&&doc?<DocEditor doc={doc} clients={clients} photos={photos} catalog={catalog} company={business} saving={saving} back={()=>go(doc.kind==="invoice"?"invoices":"estimates")} change={setDoc} save={saveDoc} remove={removeDoc} duplicate={duplicate} onPdf={()=>exportPdf(doc)} onPreview={()=>setPreviewDoc(doc)} onEmail={()=>setEmailDoc(doc)} upload={upload} deletePhoto={deletePhoto} saveLine={saveLine}/>:null}
 </div></main><nav className="mobile-nav" aria-label="Mobile navigation">{mobile.map(([v,Icon,label])=><button key={v} className={view===v||v==="more"&&(view==="profile"||view==="company")?"active":""} onClick={()=>go(v)}><Icon size={21}/><span>{label}</span></button>)}</nav></div>
 {previewDoc&&<PdfPreview doc={previewDoc} client={clients.find(c=>c.id===previewDoc.clientId)||previewDoc.clientSnapshot} company={business} profile={profile} photos={photos} onClose={()=>setPreviewDoc(null)}/>}
 {emailDoc&&<EmailComposer doc={emailDoc} client={clients.find(c=>c.id===emailDoc.clientId)||emailDoc.clientSnapshot} company={business} profile={profile} photos={photos} onClose={()=>setEmailDoc(null)} onNotice={flash} onError={setError}/>}</>
}


