export type Client={id:string;name:string;company:string;email:string;phone:string;billingAddress:string;siteAddress:string;notes:string};
export type Item={id:string;description:string;quantity:number;unit:string;unitPriceCents:number;taxable:boolean};
export type Doc={id:string;clientId:string|null;kind:"estimate"|"invoice";number:string;title:string;status:string;issueDate:string;dueDate:string;province:string;taxRate:number;discountCents:number;depositCents:number;notes:string;terms:string;items:Item[];clientSnapshot:Partial<Client>;updatedAt:number};
export type Features={photos:boolean;discounts:boolean;deposits:boolean;taxNumber:boolean;signature:boolean;paymentInstructions:boolean;jobAddress:boolean};
export type Letterhead={
 logoPosition:"left"|"center"|"right";logoSize:"small"|"medium"|"large";companyAlignment:"left"|"center"|"right";
 layoutMode:"auto"|"logoFirst"|"detailsFirst";headerStyle:"line"|"band"|"none";dividerWidth:"short"|"medium"|"full";dividerPosition:"left"|"center"|"right";
 topPadding:number;elementGap:number;dividerGap:number;afterDividerGap:number;dividerThickness:number;
 fontFamily:"helvetica"|"times"|"courier";nameSize:number;detailSize:number;nameColor:string;detailColor:string;dividerColor:string;
 showLogo:boolean;showName:boolean;showAddress:boolean;showEmail:boolean;showPhone:boolean;showTaxNumber:boolean;
};
export const defaultLetterhead:Letterhead={logoPosition:"left",logoSize:"medium",companyAlignment:"right",layoutMode:"auto",headerStyle:"line",dividerWidth:"full",dividerPosition:"center",topPadding:14,elementGap:5,dividerGap:7,afterDividerGap:9,dividerThickness:1,fontFamily:"helvetica",nameSize:17,detailSize:9,nameColor:"",detailColor:"#526271",dividerColor:"",showLogo:true,showName:true,showAddress:true,showEmail:true,showPhone:true,showTaxNumber:true};
export type Business={businessName:string;email:string;phone:string;address:string;taxNumber:string;paymentInstructions:string;defaultTerms:string;province:string;logoKey:string;accentColor:string;secondaryColor:string;documentStyle:"classic"|"modern"|"minimal";footerText:string;estimatePrefix:string;invoicePrefix:string;emailSubject:string;emailMessage:string;features:Features;letterhead:Letterhead};
export type Profile={displayName:string;jobTitle:string;phone:string;signature:string};
export type CatalogEntry={id:string;kind:"item"|"package";name:string;description:string;unit:string;unitPriceCents:number;taxable:boolean;items:Item[];updatedAt:number};
export type Photo={id:string;documentId:string;filename:string};
export const units=["each","sq ft","sq m","linear ft","linear m","cu yd","cu m","hour","day","week","lot","room","sheet","bag","box","tonne","lb","kg","litre","gallon","pair","set"] as const;
export const defaultFeatures:Features={photos:true,discounts:true,deposits:true,taxNumber:true,signature:true,paymentInstructions:true,jobAddress:true};
export const blankBusiness:Business={businessName:"Grand Terra Group of Companies",email:"info@grandterragroup.ca",phone:"+1-866-578-6025",address:"55 Commerce Valley West, Suite 502, Thornhill, ON L3T 7P4",taxNumber:"",paymentInstructions:"",defaultTerms:"",province:"ON",logoKey:"",accentColor:"#183f8f",secondaryColor:"#d8b36a",documentStyle:"classic",footerText:"",estimatePrefix:"EST",invoicePrefix:"INV",emailSubject:"",emailMessage:"",features:defaultFeatures,letterhead:defaultLetterhead};
export const blankProfile:Profile={displayName:"",jobTitle:"",phone:"",signature:""};
export const provinces:Record<string,[string,number,string]>={AB:["Alberta",5000,"GST"],BC:["British Columbia",5000,"GST"],MB:["Manitoba",5000,"GST"],NB:["New Brunswick",15000,"HST"],NL:["Newfoundland & Labrador",15000,"HST"],NS:["Nova Scotia",14000,"HST"],NT:["Northwest Territories",5000,"GST"],NU:["Nunavut",5000,"GST"],ON:["Ontario",13000,"HST"],PE:["Prince Edward Island",15000,"HST"],QC:["Québec",14975,"GST + QST"],SK:["Saskatchewan",5000,"GST"],YT:["Yukon",5000,"GST"]};
export const cash=(c:number)=>new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD"}).format((c||0)/100);
export const today=()=>new Date().toISOString().slice(0,10);
export const cents=(v:string)=>Math.max(0,Math.round((Number(v)||0)*100));
export const dollars=(v:number)=>(v/100).toFixed(2);
export const item=():Item=>({id:crypto.randomUUID(),description:"",quantity:1,unit:"each",unitPriceCents:0,taxable:true});
export const blankClient=():Client=>({id:"",name:"",company:"",email:"",phone:"",billingAddress:"",siteAddress:"",notes:""});
export const blankCatalog=(kind:"item"|"package"="item"):CatalogEntry=>({id:"",kind,name:"",description:"",unit:"each",unitPriceCents:0,taxable:true,items:kind==="package"?[item()]:[],updatedAt:0});
export function blankDoc(kind:"estimate"|"invoice",b:Business):Doc{return{id:"",clientId:null,kind,number:(kind==="invoice"?b.invoicePrefix:b.estimatePrefix)+"-"+new Date().getFullYear()+"-"+String(Date.now()).slice(-5),title:"",status:"draft",issueDate:today(),dueDate:"",province:b.province,taxRate:provinces[b.province]?.[1]||13000,discountCents:0,depositCents:0,notes:"",terms:b.defaultTerms,items:[item()],clientSnapshot:{},updatedAt:0}}
export function totals(d:Doc){const subtotal=Math.round(d.items.reduce((s,i)=>s+i.quantity*i.unitPriceCents,0));const taxable=Math.round(d.items.filter(i=>i.taxable).reduce((s,i)=>s+i.quantity*i.unitPriceCents,0));const after=Math.max(0,subtotal-d.discountCents);const base=subtotal?taxable*after/subtotal:0;const qc=d.province==="QC"&&d.taxRate===14975;const gst=qc?Math.round(base*0.05):0;const qst=qc?Math.round(base*0.09975):0;const tax=qc?gst+qst:Math.round(base*d.taxRate/100000);const total=after+tax;return{subtotal,tax,gst,qst,total,balance:Math.max(0,total-d.depositCents)}}
export function readClient(r:Record<string,unknown>):Client{return{id:String(r.id),name:String(r.name||""),company:String(r.company||""),email:String(r.email||""),phone:String(r.phone||""),billingAddress:String(r.billing_address||""),siteAddress:String(r.site_address||""),notes:String(r.notes||"")}}
export function readDoc(r:Record<string,unknown>):Doc{let items:Item[]=[];let clientSnapshot:Partial<Client>={};try{items=JSON.parse(String(r.items_json||"[]"))}catch{}try{clientSnapshot=JSON.parse(String(r.client_snapshot_json||"{}"))}catch{}return{id:String(r.id),clientId:r.client_id?String(r.client_id):null,kind:r.kind==="invoice"?"invoice":"estimate",number:String(r.number||""),title:String(r.title||""),status:String(r.status||"draft"),issueDate:String(r.issue_date||""),dueDate:String(r.due_date||""),province:String(r.province||"ON"),taxRate:Number(r.tax_rate||0),discountCents:Number(r.discount_cents||0),depositCents:Number(r.deposit_cents||0),notes:String(r.notes||""),terms:String(r.terms||""),items,clientSnapshot,updatedAt:Number(r.updated_at||0)}}
export function readBusiness(r:Record<string,unknown>|null):Business{if(!r)return blankBusiness;let features=defaultFeatures;try{features={...defaultFeatures,...JSON.parse(String(r.preferences_json||"{}"))}}catch{}let letterhead=defaultLetterhead;try{letterhead={...defaultLetterhead,...JSON.parse(String(r.letterhead_json||"{}"))}}catch{}return{businessName:String(r.business_name||""),email:String(r.email||""),phone:String(r.phone||""),address:String(r.address||""),taxNumber:String(r.tax_number||""),paymentInstructions:String(r.payment_instructions||""),defaultTerms:String(r.default_terms||""),province:String(r.province||"ON"),logoKey:String(r.logo_key||""),accentColor:String(r.accent_color||"#183f8f"),secondaryColor:String(r.secondary_color||"#d8b36a"),documentStyle:(["classic","modern","minimal"].includes(String(r.document_style))?r.document_style:"classic") as Business["documentStyle"],footerText:String(r.footer_text||""),estimatePrefix:String(r.estimate_prefix||"EST"),invoicePrefix:String(r.invoice_prefix||"INV"),emailSubject:String(r.email_subject||""),emailMessage:String(r.email_message||""),features,letterhead}}
export function readProfile(r:Record<string,unknown>|null):Profile{return r?{displayName:String(r.display_name||""),jobTitle:String(r.job_title||""),phone:String(r.phone||""),signature:String(r.signature||"")}:blankProfile}
export function readCatalog(r:Record<string,unknown>):CatalogEntry{let items:Item[]=[];try{items=JSON.parse(String(r.items_json||"[]"))}catch{}return{id:String(r.id),kind:r.kind==="package"?"package":"item",name:String(r.name||""),description:String(r.description||""),unit:String(r.unit||"each"),unitPriceCents:Number(r.unit_price_cents||0),taxable:Boolean(r.taxable),items,updatedAt:Number(r.updated_at||0)}}
export async function mutate(action:string,value:unknown={},id=""){const response=await fetch("/api/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,value,id})});const data=await response.json() as {error?:string;id?:string};if(!response.ok)throw new Error(data.error||"Save failed");return data}



