import type {Business,Client,Doc,Photo,Profile} from "@/lib/model";
import {cash,totals} from "@/lib/model";
import {transparentLogo} from "@/lib/logo";
const fmt=(date:string)=>date?new Date(date+"T12:00:00").toLocaleDateString("en-CA",{year:"numeric",month:"short",day:"numeric"}):"";
async function picture(url:string,isLogo=false):Promise<{data:string;ratio:number;format:"PNG"|"JPEG"}|null>{
 try{const res=await fetch(url,{cache:"no-store"});if(!res.ok)return null;const original=await res.blob(),blob=isLogo?await transparentLogo(original):original;const object=URL.createObjectURL(blob);try{const img=new Image();img.src=object;await img.decode();const scale=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));canvas.getContext("2d")?.drawImage(img,0,0,canvas.width,canvas.height);return{data:canvas.toDataURL(isLogo?"image/png":"image/jpeg",.88),ratio:canvas.width/canvas.height,format:isLogo?"PNG":"JPEG"}}finally{URL.revokeObjectURL(object)}}catch{return null}
}
export async function makePdf(documentData:Doc,client:Partial<Client>|undefined,company:Business,profile:Profile,photos:Photo[]){
 const {jsPDF}=await import("jspdf"),pdf=new jsPDF({unit:"mm",format:"a4",compress:true});pdf.setProperties({title:documentData.kind.toUpperCase()+" "+documentData.number,subject:documentData.title,author:company.businessName});
 const w=210,m=17,accent=/^#[0-9a-fA-F]{6}$/.test(company.accentColor)?company.accentColor:"#183f8f",gold=/^#[0-9a-fA-F]{6}$/.test(company.secondaryColor)?company.secondaryColor:"#d8b36a",dark="#1a2938",muted="#596979";let y=22;
 const triple=(hex:string)=>{const s=hex.replace("#","");return [parseInt(s.slice(0,2),16),parseInt(s.slice(2,4),16),parseInt(s.slice(4,6),16)] as const};
 const fill=(hex:string)=>{const [r,g,b]=triple(hex);pdf.setFillColor(r,g,b)},stroke=(hex:string)=>{const [r,g,b]=triple(hex);pdf.setDrawColor(r,g,b)},ink=(hex:string)=>{const [r,g,b]=triple(hex);pdf.setTextColor(r,g,b)};
 const text=(value:string,x:number,top:number,size=10,bold=false,max=0)=>{pdf.setFont("helvetica",bold?"bold":"normal");pdf.setFontSize(size);ink(bold?dark:muted);const lines=max?pdf.splitTextToSize(value||"",max):[value||""];pdf.text(lines,x,top);return top+lines.length*size*.42+2};
 const line=(top:number)=>{stroke("#dce3e9");pdf.setLineWidth(.25);pdf.line(m,top,w-m,top)};
 const footer=()=>{const pages=pdf.getNumberOfPages();for(let n=1;n<=pages;n++){pdf.setPage(n);line(278);text(company.footerText||(company.letterhead.showName?company.businessName:""),m,284,8,false,145);text(n+" / "+pages,w-m-12,284,8)}};
 const fresh=()=>{pdf.addPage();y=21},reserve=(height:number)=>{if(y+height>269)fresh()};
 const label=(value:string,x:number,top:number)=>{pdf.setFont("helvetica","bold");pdf.setFontSize(8);ink(accent);pdf.text(value.toUpperCase(),x,top)};
 const design=company.letterhead,logo=design.showLogo&&company.logoKey?await picture("/api/company-logo",true):null;
 const font=design.fontFamily||"helvetica",nameColour=design.nameColor||accent,detailColour=design.detailColor||muted,dividerColour=design.dividerColor||gold;
 const details=[design.showName&&company.businessName?{value:company.businessName,size:design.nameSize||17,bold:true,colour:nameColour}:null,design.showAddress&&company.address?{value:company.address,size:design.detailSize||9,bold:false,colour:detailColour}:null,design.showEmail&&company.email?{value:company.email,size:design.detailSize||9,bold:false,colour:detailColour}:null,design.showPhone&&company.phone?{value:company.phone,size:design.detailSize||9,bold:false,colour:detailColour}:null,design.showTaxNumber&&company.taxNumber&&company.features.taxNumber?{value:"Tax no. "+company.taxNumber,size:design.detailSize||9,bold:false,colour:detailColour}:null].filter((entry):entry is {value:string;size:number;bold:boolean;colour:string}=>Boolean(entry));
 const startY=design.topPadding||14,logoWidth=logo?Math.min(({small:25,medium:36,large:48}[design.logoSize]||36),23*logo.ratio):0,logoHeight=logo?logoWidth/logo.ratio:0;
 const logoX=design.logoPosition==="left"?m:design.logoPosition==="center"?(w-logoWidth)/2:w-m-logoWidth;
 const align=design.companyAlignment,detailX=align==="left"?m:align==="center"?w/2:w-m;
 const sideBySide=Boolean(logo&&details.length&&design.layoutMode==="auto"&&((design.logoPosition==="left"&&align==="right")||(design.logoPosition==="right"&&align==="left")));
 const detailWidth=sideBySide?Math.max(45,w-2*m-logoWidth-(design.elementGap||0)-6):w-2*m;
 const renderDetails=(top:number)=>{let cursor=top;for(const entry of details){pdf.setFont(font,entry.bold?"bold":"normal");pdf.setFontSize(entry.size);ink(entry.colour);const lines=pdf.splitTextToSize(entry.value,detailWidth) as string[];const step=entry.size*.42;pdf.text(lines,detailX,cursor+step,{align});cursor+=lines.length*step+1.4}return details.length?cursor-1.4:top};
 let contentEnd=startY;
 if(sideBySide){if(logo)pdf.addImage(logo.data,"PNG",logoX,startY,logoWidth,logoHeight);contentEnd=Math.max(startY+logoHeight,renderDetails(startY))}
 else{const logoFirst=design.layoutMode!=="detailsFirst";const gap=logo&&details.length?design.elementGap:0;if(logoFirst){if(logo)pdf.addImage(logo.data,"PNG",logoX,startY,logoWidth,logoHeight);contentEnd=startY+logoHeight;if(details.length)contentEnd=renderDetails(contentEnd+gap)}else{if(details.length)contentEnd=renderDetails(startY);if(logo){const logoTop=contentEnd+gap;pdf.addImage(logo.data,"PNG",logoX,logoTop,logoWidth,logoHeight);contentEnd=logoTop+logoHeight}}}
 const dividerY=contentEnd+(design.dividerGap||0),dividerWidth=design.dividerWidth==="short"?55:design.dividerWidth==="medium"?105:w-2*m,dividerX=design.dividerPosition==="left"?m:design.dividerPosition==="right"?w-m-dividerWidth:(w-dividerWidth)/2;
 if(design.headerStyle==="line"){fill(dividerColour);pdf.rect(dividerX,dividerY,dividerWidth,design.dividerThickness||1,"F")}else if(design.headerStyle==="band"){fill(dividerColour);pdf.rect(dividerX,dividerY,dividerWidth,Math.max(3,design.dividerThickness||1),"F")}
 y=dividerY+(design.headerStyle==="none"?0:Math.max(design.headerStyle==="band"?3:1,design.dividerThickness||1))+(design.afterDividerGap||9)+4;
 pdf.setFont(font,"bold");pdf.setFontSize(14);ink(accent);pdf.text(documentData.kind.toUpperCase(),m,y);y+=12;
 label("Document no.",m,y);text(documentData.number,m,y+6,11,true);label("Issued",75,y);text(fmt(documentData.issueDate),75,y+6,10);if(documentData.dueDate){label(documentData.kind==="invoice"?"Due date":"Valid until",137,y);text(fmt(documentData.dueDate),137,y+6,10)}y+=19;line(y);y+=12;
 label("Prepared for",m,y);y+=7;
 let to=y;to=text(client?.name||"Client",m,to,10,true,170);if(client?.company)to=text(client.company,m,to,9,false,170);if(client?.billingAddress)to=text(client.billingAddress,m,to,9,false,170);if(client?.email)to=text(client.email,m,to,9,false,170);if(client?.phone)to=text(client.phone,m,to,9,false,170);y=to+5;
 if(client?.siteAddress&&company.features.jobAddress){label("Job site",m,y);y=text(client.siteAddress,m,y+6,9,false,170)+4}
 if(documentData.title){reserve(16);y=text(documentData.title,m,y+4,15,true,170)+5}
 reserve(24);if(company.documentStyle==="minimal"){line(y+10);ink(accent)}else{fill(company.documentStyle==="modern"?dark:accent);pdf.rect(m,y,w-2*m,10,"F");ink("#ffffff")}pdf.setFont("helvetica","bold");pdf.setFontSize(8);pdf.text("DESCRIPTION",m+3,y+6.5);pdf.text("QTY / UNIT",116,y+6.5);pdf.text("RATE",155,y+6.5,{align:"right"});pdf.text("AMOUNT",w-m-3,y+6.5,{align:"right"});y+=14;
 for(const [rowIndex,row] of documentData.items.entries()){const desc=pdf.splitTextToSize(row.description||"Item",89) as string[],rh=Math.max(11,desc.length*4.5+5);reserve(rh+4);if(company.documentStyle==="modern"&&rowIndex%2===1){fill("#f1f5f7");pdf.rect(m,y-1,w-2*m,rh+2,"F")}ink(dark);pdf.setFont("helvetica","normal");pdf.setFontSize(9);pdf.text(desc,m+3,y+4);pdf.text(String(row.quantity)+" "+row.unit,116,y+4);pdf.text(cash(row.unitPriceCents),155,y+4,{align:"right"});pdf.text(cash(Math.round(row.quantity*row.unitPriceCents)),w-m-3,y+4,{align:"right"});y+=rh;if(company.documentStyle!=="minimal")line(y);y+=3}
 const total=totals(documentData);reserve(46);const right=135,sum=(name:string,value:string,bold=false)=>{pdf.setFont("helvetica",bold?"bold":"normal");pdf.setFontSize(bold?12:9);ink(bold?accent:muted);pdf.text(name,right,y);pdf.text(value,w-m,y,{align:"right"});y+=bold?9:7};
 sum("Subtotal",cash(total.subtotal));if(documentData.discountCents)sum("Discount","-"+cash(documentData.discountCents));if(total.gst){sum("GST (5%)",cash(total.gst));sum("QST (9.975%)",cash(total.qst))}else sum("Tax ("+documentData.taxRate/1000+"%)",cash(total.tax));stroke(gold);pdf.setLineWidth(.7);pdf.line(right,y,w-m,y);y+=7;sum("Total CAD",cash(total.total),true);if(documentData.depositCents)sum(documentData.kind==="invoice"?"Balance due":"After deposit",cash(total.balance),true);
 const block=(heading:string,value:string)=>{if(!value)return;const lines=pdf.splitTextToSize(value,w-2*m) as string[];reserve(lines.length*5+18);y+=5;label(heading,m,y);y=text(value,m,y+6,9,false,w-2*m)+4};block("Notes",documentData.notes);block("Terms",documentData.terms);if(documentData.kind==="invoice"&&company.features.paymentInstructions)block("Payment instructions",company.paymentInstructions);if(company.features.signature){const signature=profile.signature||[profile.displayName,profile.jobTitle,company.letterhead.showName?company.businessName:""] .filter(Boolean).join(" · ");block("Prepared by",signature)}
 if(company.features.photos&&photos.length){for(const photo of photos){const image=await picture("/api/photos?id="+encodeURIComponent(photo.id));if(!image)continue;fresh();label("Job photo",m,y);y+=7;const width=w-2*m,height=Math.min(225,width/image.ratio);pdf.addImage(image.data,"JPEG",m,y,width,height);y+=height+8;text(photo.filename,m,y,9)}}
 footer();const blob=pdf.output("blob"),safe=documentData.number.replace(/[^a-zA-Z0-9_-]+/g,"-")||documentData.kind;return new File([blob],safe+".pdf",{type:"application/pdf"})
}
export function downloadPdf(file:File){const url=URL.createObjectURL(file),anchor=document.createElement("a");anchor.href=url;anchor.download=file.name;document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}



